import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
//@ts-ignore
import "./globals.css";
import localFont from 'next/font/local';

const geistSans = localFont({
  variable: "--font-geist-sans",
  src:'../../public/fonts/Geist-VariableFont_wght.ttf',
});

const geistMono = localFont({
  src: '../../public/fonts/GeistMono-VariableFont_wght.ttf',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  title: "Dashboard DAC",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
    shortcut: "/favicon.svg",
    apple: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="fr">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
        {children}
      </body>
    </html>
  );
}
